env:
  global:
    - secure: Vfx/6/be8EHzZRQO5MTdz/+cK1fvds/GW0hAQrOJvhvIUO1OlfnLkeq4a6ZT6bPTLT5XI364Uf6tX5vlzQgiBCHLcfkPC6TblcyN9YIUzT9a54maab41vYj98LcjFfq+FA35a5typhj2NgfPV8vrz3KP1OaY0RtSz+1jrU0GJ/ZfsF+KaLa8vXJeBqPlnbd5NKhQnx7vZoOOUzGTLgeA65bTNarv5MxJ5Q0ZaUhr77JdhDKkySyBDKMQXVCtcgzVOxU6CPBKtgHiFKrCG4SQV402HNUZTdUcU7kf2XhydzIYu+fbNFpj+MqbQJo0suocdBB7nYuDLefajY2RuvZdRI//lAxXy5W+e30AcwzB8WUHQTbfbt5t8pOy/rOVwT1TGNV9QkQthcV76x7PZTUKOGgUPFeaUkpb19xdCd9YGzr/W3MZVfCSTzKGqKHGnfdwIjLrUXHYJBGd0BjfCInFpCMFhtzw4rQNDN2bHpJ/y8R+fC9HtQH7mHzSTz8X57xx6gvwz679sLT5LAjVLe1qlkfqf730kn8OJ+cpwgNn7vd3+JftqFgdCpUFR/jZF2IOBDjlUh5Un8OfT85VcvqtyGPPMEee4l+AEctFvyswq0+vf3YmPeJ4uoHUtmjz3rOSD3zewg8Uc228QBdVorVW+9dVHQJWgSEwMg+cNSeSHK0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_domains
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
