env:
  global:
    - secure: Uc+rZDYep5V5u2Eku4Z2n+HUP943jYPnPzw2IFi2BbXpw/zapc0c18PA/EiSZLlq8PMH9D0WRVLcd1Wnf8zBx2rvEaPjTT5Gnzsm9ZfsJ2h3igzdvhIccATdah3ws34aQEZd046GAw3oW4p/Gf2Jxf1itiuLeXQhgoaJNRKVuiV6QOOdnZHwGpDGJMENb5pueG1fhoeho749vNdXLD8UGmQlByrO5wl1YA6c9uXInu0crrhWgMgHW8pVu/ajwV5Td4UW+IUj+CZOtPDxELBowiJifr9uzRYg3cX7v1l+FucbJ9sTbv2V8He1rVIQhhjtt9NftJoMHQaZ1aAgzUItJ6oZoT+omdgLmv/AIAh89SoM6tfFnTniuKNT9tkG2x1isaFSj3yKtUya2JfjBS4xdrTgqw98yp5XVkIwBa70mzOQWOUZQlmkILhbbYfDz6zyq/nZ8GckZ7m4GfuvpIN6y4YOikQs1mbV28aef4T4Q+hs2QhTFEQVhhDE7/HPr5a2n3upd2duWOfDhpvCTcme5IbcM/T43T83r31r/Qs+B/XeD/g6wpV1LXabImqn/U7eXFARLgR6R37lHqYU4F05mFPX9K5mN0/93ZG6G2ors5UokgoG+AgoaQszlnpL9UOFMNtI0YdKY/OV2NvoN7eiV8me9iAMlOK0fqL3oUbzRpk=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_domains
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
