env:
  global:
    - secure: s6FgK6DudooghN/f6ZY4A2Xw/skDjBQlv7bPh4PFZ7IcaAIR5Kd7MY1orXOEP+diaaoMy/ITZwQSjw4udwNlzoQ7XYpqLYu92zyV2X1vuMPQY3L8CBS+5OwFzCDCznrqhIwhnC1Ne4XikfKA5tJYTOZHnzefwNj9zdzA+tVo351Yk81HKDUzqTlIfuTlgDh+tjWB950JWlEDS5McE9ND1hxF6wom80gURN8KdgJVYcQQUSvffs73y/YAK+8VE5fvYKD2DvaNsJQ32FvB/dWf858mS6Vyy6U8DdodiS+/LcCC/aMCZjA9PINg59hOH/c/Hcl6f+BoS6wlY6Vsk9F9t0nfk95gFkpfP6Q56snaJ97ZCHOG8k+VoBmOXolI9LQqSoOx/NGtrpIM3IRmwq00Zg3WJuRPwSlOcoMXY1tsB7qlP+kCs7fkfjElZ+gMLEgDFaYP2n+4NsAuWm04RkU3Lj4+VN3od+tZmS0KvZ+339NnZsLfs8EJjBMhY17fHy6l42kqWUADCwL90nvYxnfysKoVTr1De1570toZ1ZYkA2UVleqdL1bydi6cf327cTf4UAUXdQ/Q8Tbtv98x7acDMOtl2V9UEAqjD5KjZkuqmOd5BVnNRyERDDs9q+W86F5gofYdQ/Y52rI+Fpnx2vYxuoVgjsHEeP7Tjsgc2bRGxd0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_domains
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
