env:
  global:
    - secure: dhkA2MmQHKPXygJjMQAMA3wZVTOP2okvPHFb4FOq6O674sQN1o/nbaMMm004s3Af12mxOQGc8gAvtAOU5ihCKjWeV7AyMSPQ1WbBOFLpiLLpyqa32Pz08mJm1pdsCwsk2KTCwfv6FAEPx5rBVZ2kmDE9UD5mpOsJusueOSdUdpkyWgrznWYS/4Ex+JY5KPt5v7E7TUzgPWBL3RTqBi++F1BOsMbkVMxGP8M9LOeTARPmTe9RRG8ZylSVanSGpksN34JqqB0KlZnMv2VWfz5PKdvUbXdZy+tTZpgx8bY49T68/2Vpw6JMMfhbwC3fpyv07/VMWtNJXG+7iY4huTs2XrwtBej0lVr6fkcceZRbiPZBupq/LPKR7gAYxgwuLVefej5UCVGXNzXXEKquDJQ7HUaO8x+MKedmDmtrvKXKPPk4Lv2wNSmazcA4uHf7I0MhX8rJSWpzVmrs+12GGRa25VjNgQzdjLW41b0BTaDCVLmor6AhP4KjtQbR74A+lSKOXC99H6HsUP8r9Y0bR9DSwwp9Pq/UnGoLQNruBWd6Qmu4f9PDqQb0CPNLfHeyD0xNNvjkdmj9fEuiVpG2HapT5u58B12aM3EQvmO35Axejfn2yHwBNhY/2YUE3EB449Wl1jln90KLz2mNRBflky96o3otDYRod2igqFoktDbuGVA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_domains
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
