env:
  global:
    - secure: ISN3qUzdZsnxPMcKCWwiPNFHMWQTp5nE4el7pDRibjJwXs8R22a1oScmveKzk800+AGv81A0ou08V3BFjX5dZNSMUNgC/I8NTstGLUlxz0v6ABBYq6uMYyRbGshuYaUxvpWHHou/R/nBWgo09gh7Vekvt+wZIkCIH7C/01JICoArwEHx7A1a/QUZsU6u3gBqoWo1haJYdHxkXe8FBdTymfx/NYvrC4k3ODvedAn3tKXMajpY6nOB6GHcQCDjP/AvcT2gFsvhIc7eDECLx/0+le3+1NRukGAkHicD7dow73xEnR5l+BkKiLI8Gwi4iRsOq8Tqjd6r57v0yk9AP/w6hxQBGsfznierlX/ce/RgIT1W0nnMuZ5ViswS5RJlGZA4HFlBsQO8fHWxwm0wP4GTiFzREWTJUHIe1bwHiL6W5FydxiIDqKQ6L6NwiC4eK6aVWlvdgV/X+e0BHFr9fj1ez3LZCNUgBBAwVLv1GbrBCPufk3Ro/yMawHCKzCzpimQv9sRS95KA4u7mtj+qNflwn67y0zxR0h9pIn0hhL7xUNSOTQAz1z7FYkcr14vOUv1yC7DoMee7V9aLX5e0qQIZCgwD/lCJdvxezkfrkG0i9kx8DFfLAjWdgGqQ7YIiKKdUJ6PmK5NG2VcoEa4ojPzfq0YI2lgmCMj38uUdJgIDuUI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/yoyo.org_domains
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
